language: bash
services: docker

env:
  - VERSION=trunk
  - VERSION=trunk/alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
  - cd "$VERSION"
  - source "$TRAVIS_BUILD_DIR/scripts/set_envs.bash"

script:
  - |
    (
      set -Eeuo pipefail
      set -x

      docker build -t "$trunk_image" .
      ~/official-images/test/run.sh "$trunk_image"
      docker tag "$trunk_image" "$revision_image"

      if [ -d passenger ]; then
        docker build -t "${trunk_image}-passenger" \
          --build-arg BASE_IMAGE="${trunk_image}" \
          passenger
        ~/official-images/test/run.sh "${trunk_image}-passenger"
        docker tag "${trunk_image}-passenger" "${revision_image}-passenger"
      fi
    )

after_script:
  - docker images

deploy:
  provider: script
  script: bash "$TRAVIS_BUILD_DIR/scripts/deploy.bash"
  skip_cleanup: true
  on:
    branch: [master, deploy-test]

# vim:set et ts=2 sw=2:
