language: bash
services: docker

env:
  - VERSION=trunk
  - VERSION=trunk/alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
  - cd "$VERSION"
  - source "$TRAVIS_BUILD_DIR/scripts/set_envs.bash"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" --build-arg revision .
      ~/official-images/test/run.sh "$image"
      if [ -d passenger ]; then
        docker build -t "$image-passenger" \
          --build-arg revision \
          --build-arg BASE_IMAGE="$image" \
          passenger
        ~/official-images/test/run.sh "$image-passenger"
      fi
    )

after_script:
  - docker images

deploy:
  provider: script
  script: bash "$TRAVIS_BUILD_DIR/scripts/deploy.bash"
  on:
    branch: [master, deploy-test]

# vim:set et ts=2 sw=2:
