language: bash
services: docker

env:
  - VERSION=trunk
  - VERSION=trunk/alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
  - cd "$VERSION"
  - image="vzvu3k6k/redmine:${VERSION//\//-}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" .
      ~/official-images/test/run.sh "$image"
      if [ -d passenger ]; then
        docker build -t "$image-passenger" passenger
        ~/official-images/test/run.sh "$image-passenger"
      fi
    )

after_script:
  - docker images

deploy:
  provider: script
  script: |
    (
      set -Eeuo pipefail
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      docker push "$image"
      if [ -d passenger ]; then
        docker push "$image-passenger"
      fi
    )
  on:
    branch: [trunk, push-test]

# vim:set et ts=2 sw=2:
